# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deco < Formula
  desc "DockerEvironmentCOntrol"
  homepage "https://github.com/YaleUniversity/deco"
  version "1.4.3-pre"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.3-pre/deco_1.4.3-pre_darwin_amd64.tar.gz"
      sha256 "d7f6b4469f1a9ac41603ab88d3a21ea3c1bce029022ba6109fdd071c73ef5c8e"

      def install
        bin.install "deco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.3-pre/deco_1.4.3-pre_darwin_arm64.tar.gz"
      sha256 "9f931c3534a354017f03837ecce0316ce160103f19f015740faa2091aa3ee44b"

      def install
        bin.install "deco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.3-pre/deco_1.4.3-pre_linux_arm64.tar.gz"
      sha256 "c2dc276c6faafeef5e4051d9a0e555e90d6aa604ca15fdf0ac344cd77b739437"

      def install
        bin.install "deco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.3-pre/deco_1.4.3-pre_linux_amd64.tar.gz"
      sha256 "3065e45c8ec850fa0ef211476c7f386bcb43d2396f7aa284e9ada3dbd1411276"

      def install
        bin.install "deco"
      end
    end
  end

  test do
    system "#{bin}/deco", "version"
  end
end
