# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deco < Formula
  desc "DockerEvironmentCOntrol"
  homepage "https://github.com/YaleUniversity/deco"
  version "1.4.6-pre"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.6-pre/deco_1.4.6-pre_darwin_arm64.tar.gz"
      sha256 "bc48ed71ef9222ca1dfd59b0fab6919db4a16411f127bf3a159db2e093d66f61"

      def install
        bin.install "deco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.6-pre/deco_1.4.6-pre_darwin_amd64.tar.gz"
      sha256 "0a240c353a1c435abdba05af69be6ca26b10726e38107c556d20332836938d23"

      def install
        bin.install "deco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.6-pre/deco_1.4.6-pre_linux_arm64.tar.gz"
      sha256 "37e7e5ddaf9f054f0d24afd0d17003db3e6d619002a5cbf60a1a0a71bf0aaa4b"

      def install
        bin.install "deco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleUniversity/deco/releases/download/v1.4.6-pre/deco_1.4.6-pre_linux_amd64.tar.gz"
      sha256 "9c149a2ab1b0c6387ad773161e3b01cc6bac8fbb53ef428e27bbb0157883ff29"

      def install
        bin.install "deco"
      end
    end
  end

  test do
    system "#{bin}/deco", "version"
  end
end
