# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splat < Formula
  desc "Bootstrap new Spinup APIs"
  homepage "https://github.com/YaleSpinup/splat"
  version "0.4.10"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.10/splat_0.4.10_darwin_arm64.tar.gz"
      sha256 "287ab878ef3225edc1bbaa211e1c4785d9b6ad4a8f920c87ce80545263a04449"

      def install
        bin.install "splat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.10/splat_0.4.10_darwin_amd64.tar.gz"
      sha256 "e27a9df1ec740c5234e6aa6a1b0bf8bc393b075cb6ac311e6760582b00e0dc5d"

      def install
        bin.install "splat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.10/splat_0.4.10_linux_amd64.tar.gz"
      sha256 "f0a29714c2ab0bb3aa14b11df2e79b5c1b12bf99fbd54d8420b310addb671c33"

      def install
        bin.install "splat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.10/splat_0.4.10_linux_arm64.tar.gz"
      sha256 "d30b6a4a9aab9d52af955c3f98c54b621fb496d1940f768ac4432082c46e2f13"

      def install
        bin.install "splat"
      end
    end
  end

  test do
    system "#{bin}/splat", "version"
  end
end
