# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splat < Formula
  desc "Bootstrap new Spinup APIs"
  homepage "https://github.com/YaleSpinup/splat"
  version "0.4.8-pre"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.8-pre/splat_0.4.8-pre_darwin_arm64.tar.gz"
      sha256 "03d6f0938983a5c14c377e6edfb1257d8db723c47cfbeded448ff02c156a3556"

      def install
        bin.install "splat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.8-pre/splat_0.4.8-pre_darwin_amd64.tar.gz"
      sha256 "04427efe292c3ec73835f2cfe2b03e5851c7560ed428e89bd25325496634f59d"

      def install
        bin.install "splat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.8-pre/splat_0.4.8-pre_linux_amd64.tar.gz"
      sha256 "29c7004f295be9a90dd95dbf00bc0ac6f4846457b2f511144f379fb32ae49598"

      def install
        bin.install "splat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/splat/releases/download/v0.4.8-pre/splat_0.4.8-pre_linux_arm64.tar.gz"
      sha256 "38483c9d817b416dfafe4143e9227b596c1eda1ce3f1a8d531bac35e2bafd1d7"

      def install
        bin.install "splat"
      end
    end
  end

  test do
    system "#{bin}/splat", "version"
  end
end
