# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toker < Formula
  desc "Simple token management tool"
  homepage "https://github.com/YaleSpinup/toker"
  version "0.2.9"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.9/toker_0.2.9_darwin_amd64.tar.gz"
      sha256 "fab642646fe0a76ed3a937152d2e23461b5c21f4324ee376cb7165a82516ae0d"

      def install
        bin.install "toker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.9/toker_0.2.9_darwin_arm64.tar.gz"
      sha256 "396e6b7c845c12a5e6bbddaa70b714daf32e8a5549d96a43b76cfd3d847179bf"

      def install
        bin.install "toker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.9/toker_0.2.9_linux_amd64.tar.gz"
      sha256 "e57a87ce5ffd09e04a3b6d08f81ed4d5f879824078c8e24f4dc5ce5b30fc1b12"

      def install
        bin.install "toker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.2.9/toker_0.2.9_linux_arm64.tar.gz"
      sha256 "25edc33171a5666ab0f1f6b0e47e93791feb82bd158253003910013201fd5709"

      def install
        bin.install "toker"
      end
    end
  end

  test do
    system "#{bin}/toker", "version"
  end
end
