# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toker < Formula
  desc "Simple token management tool"
  homepage "https://github.com/YaleSpinup/toker"
  version "0.3.1"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.3.1/toker_0.3.1_darwin_arm64.tar.gz"
      sha256 "02d16ba40ba51a89643af7e538e4eae9123214ba2dd5591d109a9a82f92839a1"

      def install
        bin.install "toker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.3.1/toker_0.3.1_darwin_amd64.tar.gz"
      sha256 "8626eaf26ae8d8e13d7ffc64e597a196a3b5fa7cba0c6bffe15134c31252f2d6"

      def install
        bin.install "toker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.3.1/toker_0.3.1_linux_arm64.tar.gz"
      sha256 "0a3ddb861eabb66c4b55d15529cc7c4bdca1635aec1206c211fa694930be84b2"

      def install
        bin.install "toker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/YaleSpinup/toker/releases/download/v0.3.1/toker_0.3.1_linux_amd64.tar.gz"
      sha256 "a93ef9894a075c3fda4d32971ff1dc0ef3ab8aabf931f21dcb87a701b7a0753e"

      def install
        bin.install "toker"
      end
    end
  end

  test do
    system "#{bin}/toker", "version"
  end
end
